@startuml
'https://plantuml.com/class-diagram
interface Component{
+display():void
}

class A_Phone extends Component{
+display():void
}
class B_Phone extends Component{
+display():void
}

class Component_Decorator extends Component{
-cd:Component
+display():void
+Component_Decorator(Component)
'构造
}
Component_Decorator o..> Component

class JarPhone extends Component_Decorator{
+JarPhone(Component com)
+display()
+setJarPhone()
}
class Spinning_light extends Component_Decorator{
+Spinning_light(Component com)
+display()
+setJarPhone()
}
@enduml