@startuml
'https://plantuml.com/class-diagram

interface Subject{
Post : void
edit_personal_information : void
Edit_Post : void
}

class RealSubject {
Post : void
edit_personal_information : void
Edit_Post : void
}

Subject <|.. RealSubject

class Proxy{
Post : void
edit_personal_information : void
Edit_Post : void
}
Proxy ..|> Subject
@enduml