@startuml
'https://plantuml.com/class-diagram

interface Subject{
Post : boolean
edit_personal_information : boolean
Edit_Post : boolean
}

class RealSubject {
Post : boolean
edit_personal_information : boolean
Edit_Post : boolean
}

Subject <|.. RealSubject

class Proxy{
Post : boolean
edit_personal_information : boolean
Edit_Post : boolean
}
Proxy ..|> Subject
@enduml